# -*- coding: utf-8 -*-
"""Time_comp ynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHHMFYB6aaTMJutJkKzcNnhge-dVEX0w

# **Time and space complexity **
"""

# o(1)

n = int(input("enter the number"))

sum = n * (n+1)/2

print(sum)

# O(n)

num = int(input("Enter the number: "))
factorial = 1

if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    for i in range(1, num + 1):
        factorial = factorial * i

    print("The factorial is:", factorial)

#O(n²)
num = int(input("Enter the number: "))
factorial = 1

for i in range(1, num + 1):
    factorial = factorial * i

    for j in range(1, num + 1):
        pass

print("Factorial:", factorial)

#O(n³)
num = int(input("Enter the number: "))
factorial = 1

for i in range(1, num + 1):
    factorial = factorial * i

    for j in range(1, num + 1):
        for k in range(1, num + 1):
            pass

print("Factorial:", factorial)

#O(log n)
num = int(input("Enter a number: "))

i = 1

while i <= num:
    print(i)
    i = i * 2

def calculate(n):
    if n == 0:
        return

    calculate(n - 1)
    calculate(n - 1)